---
- name: Instalar Apache en Ubuntu
  hosts: all
  become: yes  # Permitir el uso de sudo
  tasks:
    - name: Actualizar los repositorios de paquetes
      apt:
        update_cache: yes

    - name: Instalar el paquete apache2
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes  # Asegura que Apache se inicie al arrancar el sistema

    - name: Asegurarse de que Apache está funcionando
      uri:
        url: http://localhost
        return_content: yes
      register: result

    - name: Mostrar el contenido de la respuesta
      debug:
        var: result.content
